### ISSUE TITLE
xsd:double support

### ISSUE THREAD

**Issue by afs** [afs/mantis#2]
TDB2 has a reorganized `NodeId` which usually has space for 56 bit encoded values inline. It also has space for 62 bits for the one case of xsd:double but there is no implementation yet.

* [Details of `xsd:double`](https://www.w3.org/TR/xmlschema11-2/#double), a IEEE 754 binary64.
* [Wikipedia entry about IEEE 754-2008 binary64](https://en.wikipedia.org/wiki/Double-precision_floating-point_format).

To inline the value without increasing the size of `NodeId`, 2 bits need to be saved. Values not meeting the restriction will be stored as nodes in the node table.

Proposal: keep the significand (mantissa) as 52 bits and reduce the exponent from 11 bits to 9 bits - making a size limit of inlined values 1.157921e+77, rather than the full 1.797693e+308.  

Infinities, +/- zero and NaNs are inlined.

This is recoverable - inline values will be perfected recovered.

Reducing the precision instead risks looses accuracy.

TDB2 already added the inlining of xsd:floats and retaining the datatypes of integer derived datatypes.

**Comment by ajs6f** [comment]
Two quick questions, just to check my understanding-- this means that values outside the inline limits will be pushed to the dictionary? And there will be special values for ±∞, ±0, and NaN that will mean that the "literal" values used for those guys will also get pushed to the dictionary? (If they weren't going to already get pushed because of the size limits.)

**Comment by afs** [comment]
Yes - if not encode-able, the number goes to the node table.

±∞, ±0, and NaN will be encode-able and not go to the dictionary (they are handled as special exponents in IEEE 754 - TDB2 can do the same except with a 9 bits exponent, not an 11 bit one).

**Comment by ajs6f** [comment]
👍
